# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://cvc.bike'
baseurl: ''
title: 'Cumberland Valley Collective'
description: 'CVC'
permalink: pretty
logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/CVC_Capital_Partners_logo.svg/200px-CVC_Capital_Partners_logo.svg.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Sponsors
  url: /sponsors/
- title: Blog
  url: /blog/


# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "Race reports, ride stories, and other news"
    feature_text: |
      Cumberland Cycling Collective Blog
    feature_image: "https://picsum.photos/2560/600?image=866"
