# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://cvc.bike'
baseurl: ''
title: 'Cumberland Valley Collective'
description: 'CVC'
permalink: pretty
logo: "/img/cvc-text.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Our Mission
  url: /ourmission/
- title: Team
  url: /team/
- title: Sponsors
  url: /sponsors/
- title: Events
  url: /events/
- title: Blog
  url: /blog/
- title: Store
  url: /store/
- title: Instagram
  url: http://instagram.com/cvc.bike
  image: /img/logo_ig.png


# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: 
    output: true
    description: "Race reports, ride stories, and other news"
    feature_text: |
      <div style="display:none">Cumberland Cycling Collective Blog</div>
    feature_image: "/img/ian-climb.jpg"
